ACCOUNTS=["GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6", "GB7EKKXHOCCMVN5SQNJ6IVILY53KSVH2DPMJ66P6272CWCJO7DUJMFVZ"]

[DOCUMENTATION]
ORG_NAME="PiRC-207 RWA Sovereign System"
ORG_URL="https://ze0ro99.github.io/PiRC"

[[CURRENCIES]]
code="PURPLE"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Registry Layer (L0)"
desc="Foundation Registry | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/purple.png"

[[CURRENCIES]]
code="GOLD"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Reserve Layer (L1)"
desc="Reserve Asset | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/gold.png"

[[CURRENCIES]]
code="YELLOW"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Utility Layer (L2)"
desc="Transactional Tier | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/yellow.png"

[[CURRENCIES]]
code="ORANGE"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Settlement Layer (L3)"
desc="Settlement Hub | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/orange.png"

[[CURRENCIES]]
code="BLUE"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Liquidity Layer (L4)"
desc="Stability Guardrail | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/blue.png"

[[CURRENCIES]]
code="GREEN"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="PiCash Standard (L5)"
desc="Cash Benchmark | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/green.png"

[[CURRENCIES]]
code="RED"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Governance Layer (L6)"
desc="Governance Matrix | Official PiRC-207 Ecosystem Layer | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/red.png"

