ACCOUNTS=["GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"]

[[CURRENCIES]]
code="PURPLE"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 0 - Root Registry"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/purple.png"

[[CURRENCIES]]
code="GOLD"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 1 - Reserve Currency"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/gold.png"

[[CURRENCIES]]
code="YELLOW"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 2 - Utility Tier"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/yellow.png"

[[CURRENCIES]]
code="ORANGE"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 3 - Governance"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/orange.png"

[[CURRENCIES]]
code="BLUE"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 4 - Liquidity"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/blue.png"

[[CURRENCIES]]
code="GREEN"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 5 - Ecosystem"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/green.png"

[[CURRENCIES]]
code="RED"
issuer="GA3ECRFJ6SO5BW6NEIKW3ACJXNG5UNBTLRRXWC742NHUEDV6KL3RNEN6"
display_decimals=7
name="Layer 6 - Settlement"
desc="Official PiRC-207 RWA Asset | Registry: CAEUNHEUXACISTVHICFNISFRTRVSK5IALA3H5MUT7P4JKU5L3IPSKG4B"
image="https://ze0ro99.github.io/PiRC/images/red.png"

